package com.academy.ecommerce.sterling.util.webservice;

import java.util.Random;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

import com.academy.ecommerce.sterling.util.AcademyPayeezyRestUtil;
import com.academy.util.constants.AcademyConstants;
import com.academy.util.xml.XMLUtil;
import com.yantra.yfc.dom.YFCDocument;
import com.yantra.yfc.log.YFCLogCategory;
import com.yantra.yfs.japi.YFSEnvironment;

public class AcademyRTSPLCCUtil {

	private static YFCLogCategory log = YFCLogCategory.instance(AcademyRTSPLCCUtil.class);
	
	
	
	public static Document sendDummyHTTP(Document requestXMLDoc) throws Exception {

		log.verbose("Begin of AcaddemyRTSWebserviceForPLCC.sendDummyHTTP() method");

		int iRandm6 = 100000 + new Random().nextInt(900000);
		int iFirstRandm8 = 10000000 + new Random().nextInt(90000000);
		int iSecondRandm8 = 10000000 + new Random().nextInt(90000000);
		Random r = new Random();
		long lRandom11 = 1000000000L + (long)(r.nextDouble() * 999999999L);
		String strReversalId = AcademyPayeezyRestUtil.getAutoGeneratedUUID();

		Document docResponse = YFCDocument.createDocument(AcademyConstants.ATTR_RTS_XMLAJB_IPAY_RESPONSE).getDocument();
		Element eleResponse = docResponse.getDocumentElement();

		Element eleIxCmd = docResponse.createElement(AcademyConstants.ATTR_RTS_CMD);
		Element eleIxActionCode = docResponse.createElement(AcademyConstants.ATTR_RTS_ACTION_CODE);
		Element eleIxDebitCredit = docResponse.createElement(AcademyConstants.ATTR_RTS_DEBIT_CREDIT);
		Element eleIxTermid = docResponse.createElement("IxTermid");
		Element eleIxStoreNumber = docResponse.createElement(AcademyConstants.ATTR_RTS_STORE_NUM);
		Element eleIxTerminalNumber = docResponse.createElement(AcademyConstants.ATTR_RTS_TERMINAL_NUM);
		Element eleIxTranType = docResponse.createElement(AcademyConstants.ATTR_RTS_TRAN_TYPE);
		Element eleIxAccount = docResponse.createElement(AcademyConstants.ATTR_RTS_ACCOUNT);
		Element eleIxExpDate = docResponse.createElement(AcademyConstants.ATTR_RTS_EXPIRY_DATE); //date is null
		Element eleIxAmount = docResponse.createElement(AcademyConstants.ATTR_RTS_AMOUNT); 
		Element eleIxInvoice = docResponse.createElement(AcademyConstants.ATTR_RTS_INVOICE);
		Element eleIxOptions = docResponse.createElement(AcademyConstants.ATTR_RTS_OPTIONS);
		Element eleIxPosEchoField = docResponse.createElement(AcademyConstants.ATTR_RTS_POS_ECHO_FIELD);
		Element eleIxAuthCode = docResponse.createElement(AcademyConstants.ATTR_RTS_AUTH_CODE);
		Element eleIxReceiptDisplay = docResponse.createElement(AcademyConstants.ATTR_RTS_RECEIPT_DISP);
		Element eleIxPS2000 = docResponse.createElement("IxPS2000");
		Element eleIxSeqNumber = docResponse.createElement("IxSeqNumber");
		Element eleIxDate = docResponse.createElement(AcademyConstants.ATTR_RTS_DATE);
		Element eleIxTime = docResponse.createElement(AcademyConstants.ATTR_RTS_TIME);
		Element eleIxBankNodeID = docResponse.createElement("IxBankNodeID");
		Element eleIxAuthResponseTime = docResponse.createElement("IxAuthResponseTime");
		Element eleIxDebitComLink = docResponse.createElement(AcademyConstants.ATTR_RTS_DEBIT_COM_LINK);
		Element eleIxResponseTimeMilliSeconds = docResponse.createElement(AcademyConstants.ATTR_RTS_RESPONSE_TIME_MILLI_SEC);
		Element eleIxResponseDateTimeMilli = docResponse.createElement("IxResponseDateTimeMilli");
		Element eleIxNeedsReversal = docResponse.createElement(AcademyConstants.ATTR_RTS_NEEDS_REVERSAL);
		Element eleIxIsVoid = docResponse.createElement(AcademyConstants.ATTR_RTS_IS_VOID);

		eleIxCmd.appendChild(docResponse.createTextNode(requestXMLDoc.getElementsByTagName(AcademyConstants.ATTR_RTS_CMD).item(0).getTextContent()));
		eleIxActionCode.appendChild(docResponse.createTextNode(AcademyConstants.STR_ZERO));
		eleIxDebitCredit.appendChild(docResponse.createTextNode(requestXMLDoc.getElementsByTagName(
				AcademyConstants.ATTR_RTS_DEBIT_CREDIT).item(0).getTextContent()));
		eleIxTermid.appendChild(docResponse.createTextNode(AcademyConstants.STR_ONE));
		eleIxStoreNumber.appendChild(docResponse.createTextNode(requestXMLDoc.getElementsByTagName(
				AcademyConstants.ATTR_RTS_STORE_NUM).item(0).getTextContent()));
		eleIxTerminalNumber.appendChild(docResponse.createTextNode(requestXMLDoc.getElementsByTagName(
				AcademyConstants.ATTR_RTS_TERMINAL_NUM).item(0).getTextContent()));
		eleIxTranType.appendChild(docResponse.createTextNode(requestXMLDoc.getElementsByTagName(
				AcademyConstants.ATTR_RTS_TRAN_TYPE).item(0).getTextContent()));
		eleIxAccount.appendChild(docResponse.createTextNode(requestXMLDoc.getElementsByTagName(
				AcademyConstants.ATTR_RTS_ACCOUNT).item(0).getTextContent()));
		eleIxExpDate.appendChild(docResponse.createTextNode(requestXMLDoc.getElementsByTagName(
				AcademyConstants.ATTR_RTS_EXPIRY_DATE).item(0).getTextContent()));
		eleIxAmount.appendChild(docResponse.createTextNode(requestXMLDoc.getElementsByTagName(
				AcademyConstants.ATTR_RTS_AMOUNT).item(0).getTextContent()));
		eleIxInvoice.appendChild(docResponse.createTextNode(requestXMLDoc.getElementsByTagName(
				AcademyConstants.ATTR_RTS_INVOICE).item(0).getTextContent()));
		eleIxOptions.appendChild(docResponse.createTextNode(requestXMLDoc.getElementsByTagName(
				AcademyConstants.ATTR_RTS_OPTIONS).item(0).getTextContent()));
		eleIxPosEchoField.appendChild(docResponse.createTextNode(requestXMLDoc.getElementsByTagName(
				AcademyConstants.ATTR_RTS_POS_ECHO_FIELD).item(0).getTextContent()));

		//6 digit random
		eleIxAuthCode.appendChild(docResponse.createTextNode(Integer.toString(iRandm6)));

		eleIxReceiptDisplay.appendChild(docResponse.createTextNode(requestXMLDoc.getElementsByTagName(
				AcademyConstants.ATTR_RTS_TRAN_TYPE).item(0).getTextContent()));
		eleIxPS2000.appendChild(docResponse.createTextNode("&amp;amp;amp;#x1F;AS-5NN"));
		//8digit random
		eleIxSeqNumber.appendChild(docResponse.createTextNode(Integer.toString(iFirstRandm8)));
		eleIxDate.appendChild(docResponse.createTextNode(requestXMLDoc.getElementsByTagName(
				AcademyConstants.ATTR_RTS_DATE).item(0).getTextContent()));
		eleIxTime.appendChild(docResponse.createTextNode(requestXMLDoc.getElementsByTagName(
				AcademyConstants.ATTR_RTS_TIME).item(0).getTextContent()));
		eleIxBankNodeID.appendChild(docResponse.createTextNode("MPSCRD"));
		eleIxAuthResponseTime.appendChild(docResponse.createTextNode(AcademyConstants.STR_ZERO));
		//8digit random
		eleIxDebitComLink.appendChild(docResponse.createTextNode(Integer.toString(iSecondRandm8)));
		eleIxResponseTimeMilliSeconds.appendChild(docResponse.createTextNode(AcademyConstants.STR_ZERO));
		eleIxResponseDateTimeMilli.appendChild(docResponse.createTextNode("145931121"));
		eleIxNeedsReversal.appendChild(docResponse.createTextNode(strReversalId));
		//11digit random
		eleIxIsVoid.appendChild(docResponse.createTextNode(Long.toString(lRandom11)));

		eleResponse.appendChild(eleIxCmd);
		eleResponse.appendChild(eleIxActionCode);
		eleResponse.appendChild(eleIxDebitCredit);
		eleResponse.appendChild(eleIxTermid);
		eleResponse.appendChild(eleIxStoreNumber);
		eleResponse.appendChild(eleIxTerminalNumber);
		eleResponse.appendChild(eleIxTranType);
		eleResponse.appendChild(eleIxAccount);
		eleResponse.appendChild(eleIxExpDate);
		eleResponse.appendChild(eleIxAmount);
		eleResponse.appendChild(eleIxInvoice);
		eleResponse.appendChild(eleIxOptions);          ////remove
		eleResponse.appendChild(eleIxPosEchoField);
		eleResponse.appendChild(eleIxAuthCode);
		eleResponse.appendChild(eleIxReceiptDisplay);
		eleResponse.appendChild(eleIxPS2000);
		eleResponse.appendChild(eleIxSeqNumber);
		eleResponse.appendChild(eleIxDate);
		eleResponse.appendChild(eleIxTime);
		eleResponse.appendChild(eleIxBankNodeID);
		eleResponse.appendChild(eleIxAuthResponseTime);
		eleResponse.appendChild(eleIxDebitComLink);
		eleResponse.appendChild(eleIxResponseTimeMilliSeconds);
		eleResponse.appendChild(eleIxResponseDateTimeMilli);
		eleResponse.appendChild(eleIxNeedsReversal);
		eleResponse.appendChild(eleIxIsVoid);

		log.verbose("AcaddemyRTSWebserviceForPLCC.sendDummyHTTP() Payment Output XML:: "+XMLUtil.getXMLString(docResponse));
		log.verbose("End of AcaddemyRTSWebserviceForPLCC.sendDummyHTTP() method");

		return docResponse;
	} 
}
