	
/*
 * Created on May 09,2009
 *
 */
package com;

import java.util.MissingResourceException;
import java.util.ResourceBundle;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.osgi.framework.BundleContext;

import com.academy.ecommerce.sterling.util.ResourceUtil;
import com.yantra.yfc.rcp.YRCPlatformUI;

/**
 * @author sahmed
 *
 * Generated by Sterling RCP Tools
 * The main plugin class to be used in the desktop.
 * Copyright © 2005, 2006 Sterling Commerce, Inc. All Rights Reserved.
 */

public class AcademyPlugin extends AbstractUIPlugin {

	private static AcademyPlugin plugin;
    
    public static final String ID = "com.academy.ecommerce.sterling";
	
	/**
	 * The constructor.
	 */
	public AcademyPlugin() {
		super();
		plugin = this;
		try {
            YRCPlatformUI.registerPlugin(ID, this);			
			YRCPlatformUI.registerBundle("com.academy.ecommerce.sterling_bundle", ID);
			YRCPlatformUI.registerCommands("com.academy.ecommerce.sterling_commands", ID);
			YRCPlatformUI.registerTheme("com.academy.ecommerce.sterling_theme", ID);
			YRCPlatformUI.registerExtensions("com.academy.ecommerce.sterling_extn.yuix", ID);			
			ResourceUtil.loadResourceFile("/ACADEMYPCA.properties");	
		} catch (MissingResourceException x) {
            x.printStackTrace();
		}
	}

	/**
	 * This method is called upon plug-in activation
	 */
	public void start(BundleContext context) throws Exception {
		super.start(context);
	}

	/**
	 * This method is called when the plug-in is stopped
	 */
	public void stop(BundleContext context) throws Exception {
		super.stop(context);
	}

	/**
	 * Returns the shared instance.
	 */
	public static AcademyPlugin getDefault() {
		return plugin;
	}

	/**
	 * Returns the plugin's resource bundle,
	 */
	public ResourceBundle getResourceBundle() {
		return null;
	}

}
