package com.academy.som;
	
/*
 * Created on Jul 19,2013
 *
 */

import java.util.MissingResourceException;
import java.util.ResourceBundle;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.osgi.framework.BundleContext;

import com.academy.som.util.AcademyPCAConstants;
import com.yantra.yfc.rcp.YRCDesktopUI;
import com.yantra.yfc.rcp.YRCEditorInput;
import com.yantra.yfc.rcp.YRCEditorPart;
import com.yantra.yfc.rcp.YRCPlatformUI;

/**
 * Generated by Sterling RCP Tools
 * The main plugin class to be used in the desktop.
 * Copyright © 2005, 2006 Sterling Commerce, Inc. All Rights Reserved.
 */

public class AcademySOMPlugin extends AbstractUIPlugin {

	private static AcademySOMPlugin plugin;
    
    public static final String ID = "com.academy.som";
	
	/**
	 * The constructor.
	 */
	public AcademySOMPlugin() {
		super();
		plugin = this;
		try {
            YRCPlatformUI.registerPlugin(ID, this);			
			YRCPlatformUI.registerBundle("com.academy.som_bundle", ID);
			YRCPlatformUI.registerCommands("com.academy.som_commands", ID);
			YRCPlatformUI.registerTheme("com.academy.som_theme", ID);
			YRCPlatformUI.registerExtensions("com.academy.som_extn.yuix", ID);	
			//YRCPlatformUI.closeEditor("com.yantra.pca.ycd.rcp.editors.YCDQuickAccessEditor", true);
		} catch (MissingResourceException x) {
            x.printStackTrace();
		}
	}

	/**
	 * This method is called upon plug-in activation
	 */
	public void start(BundleContext context) throws Exception {
		//YRCPlatformUI.closeEditor("com.yantra.pca.ycd.rcp.editors.YCDQuickAccessEditor", true);
		//YRCPlatformUI.openEditor(AcademyPCAConstants.OOB_SHIPPING_PPT_EDITOR_ID, null);
		//ssuper.start(context);
	}

	/**
	 * This method is called when the plug-in is stopped
	 */
	public void stop(BundleContext context) throws Exception {
		super.stop(context);
	}

	/**
	 * Returns the shared instance.
	 */
	public static AcademySOMPlugin getDefault() {
		return plugin;
	}

	/**
	 * Returns the plugin's resource bundle,
	 */
	public ResourceBundle getResourceBundle() {
		return null;
	}

}
